# Generated by Django 5.2 on 2025-04-22 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_order_date_order_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoupKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='soup_kits/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soup_kits', to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='SoupKitIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('soup_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.soupkit')),
            ],
            options={
                'unique_together': {('soup_kit', 'product')},
            },
        ),
        migrations.AddField(
            model_name='soupkit',
            name='ingredients',
            field=models.ManyToManyField(related_name='soup_kits', through='store.SoupKitIngredient', through_fields=('soup_kit', 'product'), to='store.product'),
        ),
    ]
